gh: fix

diff --git a/.github/workflows/visual-test.yml b/.github/workflows/visual-test.yml
--- a/.github/workflows/visual-test.yml
+++ b/.github/workflows/visual-test.yml
@@ -1,5 +1,5 @@
 name: Visual Test
-run-name: ${{ format('Visual Test{0}{1}', (github.event.inputs.vscode_revision && github.event.inputs.vscode_revision != 'main') && format(' with VSCode {0}', github.event.inputs.vscode_revision) || '', github.event_name == 'workflow_dispatch' && '' || format(' - {0}', github.event.head_commit.message)) }}
+run-name: ${{ format('Visual Test{0}{1}', (github.event.inputs.vscode_revision && github.event.inputs.vscode_revision != 'main') && format(' with VSCode {0}', github.event.inputs.vscode_revision) || '', github.event_name != 'workflow_dispatch' && format(' - {0}', github.event.head_commit.message) || '') }}
 on:
   push:
     branches: [ main, master ]
@@ -44,15 +44,24 @@ jobs:
       run: git clone --depth 10 https://github.com/microsoft/vscode.git vscode
     - name: Checkout VSCode Revision
       run: |
-        cd vscode
-        git fetch --depth 10 origin ${{ github.event.inputs.vscode_revision }}
-        if ! git checkout ${{ github.event.inputs.vscode_revision }}; then
-          echo "Checkout failed, retrying with git checkout -b tag-${{ github.event.inputs.vscode_revision }} tags/${{ github.event.inputs.vscode_revision }} ..."
-          git checkout -b tag-${{ github.event.inputs.vscode_revision }} tags/${{ github.event.inputs.vscode_revision }}
-        fi
-        cd ..
-        # Checkout a branch if vscode_revision is not main
         if [ -n "${{ github.event.inputs.vscode_revision }}" ] && [ "${{ github.event.inputs.vscode_revision }}" != "main" ]; then
+          cd vscode
+
+          git fetch --depth 10 origin ${{ github.event.inputs.vscode_revision }}
+          if ! git checkout ${{ github.event.inputs.vscode_revision }}; then
+            echo "Direct checkout failed, trying with tag or branch name."
+
+            if ! git fetch --depth 1 origin tag ${{ github.event.inputs.vscode_revision }}; then
+              echo "Seems like this is not a tag, trying with branch name."
+              git remote set-branches origin ${{ github.event.inputs.vscode_revision }}
+              git fetch --depth 10 origin ${{ github.event.inputs.vscode_revision }}
+            fi
+            git checkout ${{ github.event.inputs.vscode_revision }}
+          fi
+
+          cd ..
+
+          # Checkout a branch if vscode_revision is not main
           git checkout -b "$(git branch --show-current)-with-vscode-${{ github.event.inputs.vscode_revision }}"
         fi
     - name: Get VSCode Version
